# Generated by Django 4.0.4 on 2024-05-23 20:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('CarroID', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=255)),
                ('Linea', models.CharField(max_length=255)),
                ('Modelo', models.CharField(max_length=10)),
                ('Transmision', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('NIT', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('CotizacionID', models.AutoField(primary_key=True, serialize=False)),
                ('VendedorID', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('DepaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('EmpleadoDPI', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Cambio',
            fields=[
                ('CambioID', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Cambio', models.CharField(max_length=50)),
                ('Tabla_Afectada', models.CharField(max_length=50)),
                ('ID_Registro', models.IntegerField()),
                ('Usuario', models.CharField(max_length=50)),
                ('Fecha', models.DateTimeField()),
                ('Comentario', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ProveedorID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Contacto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Numero_Orden', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=255)),
                ('NIT', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='apll.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('EmpleadoID', models.AutoField(primary_key=True, serialize=False)),
                ('EmpleadoDPI', models.IntegerField()),
                ('Usuario', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('RepuestoID', models.AutoField(primary_key=True, serialize=False)),
                ('CarroID', models.IntegerField()),
                ('Nombre', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=50)),
                ('Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('PagoID', models.AutoField(primary_key=True, serialize=False)),
                ('MetodoPago', models.CharField(max_length=50)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='apll.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarroID', models.IntegerField()),
                ('RepuestoID', models.IntegerField()),
                ('Existencia', models.IntegerField()),
                ('Cantidad_Minima', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.carro')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.repuestos')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles_Venta',
            fields=[
                ('Detalles_VentaID', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_Orden', models.IntegerField()),
                ('RepuestoID', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Rebaja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SubTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.repuestos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion_Detalle',
            fields=[
                ('CotizacionDetalleID', models.AutoField(primary_key=True, serialize=False)),
                ('CotizacionID', models.IntegerField()),
                ('RepuestoID', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Precio_Unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Precio_Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Numero_Linea', models.IntegerField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.cotizacion')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.repuestos')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.empleados'),
        ),
        migrations.CreateModel(
            name='Compra_Repuesto',
            fields=[
                ('CompraRepuestoID', models.AutoField(primary_key=True, serialize=False)),
                ('RepuestoID', models.IntegerField()),
                ('Costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProveedorID', models.IntegerField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.proveedor')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.repuestos')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('Cantidad', models.IntegerField()),
                ('CarroID', models.IntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('ComisionID', models.AutoField(primary_key=True, serialize=False)),
                ('EmpleadoDPI', models.IntegerField()),
                ('NumOrden', models.IntegerField()),
                ('Tipo', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.empleados')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Cambios_Salarios',
            fields=[
                ('Cambio_SalarioID', models.AutoField(primary_key=True, serialize=False)),
                ('EmpleadoDPI', models.IntegerField()),
                ('Fecha_Cambio', models.DateTimeField()),
                ('Salario_Anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Salario_Nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Motivo', models.CharField(max_length=255)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora_Alertas',
            fields=[
                ('AlertaID', models.AutoField(primary_key=True, serialize=False)),
                ('RepuestoID', models.IntegerField()),
                ('Fecha', models.DateTimeField()),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apll.repuestos')),
            ],
        ),
    ]
