# Generated by Django 5.0.4 on 2024-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='EmpleadoDPI',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
